[tool.black]
line-length = 100
target-version = ['py39']

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']

[tool.ruff]
select = [
  "A",
  "ALL",
  "ANN",
  "ARG",
  "B",
  "BLE",
  "C",
  "D",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "F",
  "FBT",
  "I",
  "IC",
  "ICN",
  "M",
  "N",
  "PD",
  "PDV",
  "PGH",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "R",
  "RET",
  "RUF",
  "S",
  "SIM",
  "T",
  "TID",
  "U",
  "UP",
  "W",
  "YTT",
]

line-length = 88
show-source = true
fix = true
